# Generated by Django 5.1 on 2025-01-20 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smart',
            name='price_range',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='projekt.pricerange'),
        ),
    ]
