# Generated by Django 5.1 on 2025-01-22 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0002_alter_smart_price_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpoVoteCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(default=1)),
                ('corpo_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter', to='projekt.corpoteam')),
                ('related_proj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_proj', to='projekt.smart')),
            ],
        ),
    ]
