# Generated by Django 5.1 on 2025-01-23 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0003_corpovotecounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='smart',
            name='working_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projekt.corpoteam'),
        ),
    ]
